### PR TITLE
update message when waiting for analysis

### LINKED ISSUE #493: change waiting analysis text
in waiting_analysis.html change

`Waiting for analysis to run`

to 

`Waiting for analysis to complete`

AND change

`The analysis is running...`

to 

`Your analysis job has been queued.`

AND change

`However, you can close this message if you want to continue working. Don't worry, we will send you an email once the analysis is finished. <br />
The larger the analysis area, the longer the analysis will take.`

to

`If it is a small job the results will appear soon. <b>Analysis jobs on large areas or with certain data layers will take longer, from minutes to possibly hours.</b>  <br /> <br />
You can close this message and continue working. The analysis will continue even if you log out or shut down. <br /> <br />
We will send you an email once the analysis is finished, or you can come back here or to the Analysis List page any time to check on progress.`

### PR DESCRIPTION
**Pull request by myarjunar**
fix #493 
@gavin there are some string unstranslated on this update (I have pushed it to transifex), I will update the PR after the strings are translated

### CODE REVIEW

**Review by lucernae — APPROVED** [review]
LGTM. Thanks @myarjunar just merge when the translation is ready.

**Comment by lucernae** [comment]
Also added User Manual link.
fix #443
screen shot 2018-11-22 at 20 33 22

**Comment by gubuntu** [comment]
please also push 'Download User Manual' to transifex for translation (if you haven't already)

**Comment by myarjunar** [comment]
> please also push 'Download User Manual' to transifex for translation (if you haven't already)

@gubuntu I will create another PR only for translation

**Pull request merged**
