### PR TITLE
Refactor QGIS Url

### PR DESCRIPTION
**Pull request by lucernae**
Need to merge this to accomodate changes in QGIS Url

### CODE REVIEW

**Comment by lucernae** [comment]
On second thought, we should actually just use geonode legend url, instead of manually reversing the url.

**Comment by Gustry** [comment]
+1 to remove this view from the qgis server app. We should use the same URL as geonode if possible

**Comment by lucernae** [comment]
I will take this @boney-bun . 
Just note that in the future it is best if we reduce dependency as much as possible. GeoSAFE didn't have to worry about QGIS Server backend, and changes should be transparent.

**Comment by boney-bun** [comment]
yes, agree with your approach @lucernae 
LGTM.

**Comment by boney-bun** [comment]
we should carefully examine the refactor before merging them.
i found that the legend no longer work properly on my local machine when imitating your code locally.

**Comment by lucernae** [comment]
It works in mine, @boney-bun . Did you use git checkout or did you put the changes manually?

screen shot 2017-06-10 at 14 48 12

**Comment by gubuntu** [comment]
@boney-bun can you confirm this works? Otherwise if you're happy @lucernae then merge

**Pull request merged**
