### PR TITLE
Fix ui

### PR DESCRIPTION
**Pull request by dimasciput**
- Fix geosafe arrow in menu ( #106 )
screen shot 2017-05-09 at 1 38 32 pm

- Update landing page ( #62 )
geosafe

### CODE REVIEW

**Comment by gubuntu** [comment]
LGTM, thanks. Just correct to 'What can GeoSAFE do?'

**Comment by dimasciput** [comment]
@gubuntu updated : https://github.com/kartoza/geosafe/pull/107/commits/6816135f68e11625eceb42fcc2850f86666b1e3c

**Comment by lucernae** [comment]
Thank's @dimasciput . I just realized that geonode changed the template name from site_base.html to geonode_base.html.

So, it will be better if you rename site_base.html to geonode_base.html (and also update the reference in index.html)

**Review by lucernae — APPROVED** [review]
LGTM.
You can squash rebase it after renaming the file name.

**Comment by gubuntu** [comment]
thanks @lucernae. @dimasciput  please do so asap then add to this PR and merge so we can get this into the demo

**Comment by gubuntu** [comment]
ping @dimasciput

**Comment by dimasciput** [comment]
on it

**Pull request merged**
