### PR TITLE
add scroll to impact list

### LINKED ISSUE #506: long analysis list needs to have max size and scroll

### PR DESCRIPTION
**Pull request by boney-bun**
fix #506

### CODE REVIEW

**Comment by gubuntu** [comment]
screenshot / gif? 

it must stay in the screen and have max width and height

**Comment by boney-bun** [comment]
screenshot:

geosafe 507

in the gif above, the max width is 300px and max height is 100px only for demo purposes.
the actual max height and max width is 300px.
the UI will be something like:
screen shot 2018-11-26 at 12 19 23 pm

what do you think @gubuntu ?

**Comment by gubuntu** [comment]
LGTM

we should do this too for the other lists (exposure, hazard and aggregation) since they could also get quite long.

**Review by myarjunar — COMMENTED** [review]
LGTM! thanks. 

one comment: I saw that the impact-list box dynamically placed a few pixels upper than the impact button (depends on the number of impact layer). wouldn't it be better if we placed it right next to the impact button (just like the input layers) if we have implemented this scroll-able box? cc @gubuntu @lucernae

**Review by myarjunar — APPROVED** [review]

**Comment by gubuntu** [comment]
I agree all the list boxes should look and behave the same as each other

**Review by lucernae — APPROVED** [review]
LGTM, thanks @boney-bun

**Comment by lucernae** [comment]
> one comment: I saw that the impact-list box dynamically placed a few pixels upper than the impact button (depends on the number of impact layer). wouldn't it be better if we placed it right next to the impact button (just like the input layers) if we have implemented this scroll-able box? cc @gubuntu @lucernae

@gubuntu @myarjunar 
I'm not sure what you meant by this, but just reply if I'm commenting about different things. The impact-list box header should be above impact button (unlike input layers), because this button is located at the bottom. In a smaller screen, if we use the same behaviour as input layers, there is not enough space to list the content vertically. I think the current behaviour is fine (bottom of impact-list box should line up with bottom of impact button).

**Comment by boney-bun** [comment]
thanks @gubuntu @myarjunar @lucernae 

i'm going to merge this.
i've created another issue (#510) for other modal windows.
i think we can continue the discussion in #510.

**Pull request merged**
