### PR TITLE
Fix overflowing legend and filter layers by permissions

### PR DESCRIPTION
**Pull request by akbargumbira**
In a small screen size, the legend is overflowing. This is to fix that by adding scrollbar whenever it's overflowing

cc @lucernae @boney-bun

### CODE REVIEW

**Comment by NyakudyaA** [comment]
#180  You can close this when merged

**Comment by akbargumbira** [comment]
ah ok, didn't know the issue exists already :)

**Comment by boney-bun** [comment]
I have 3 comments:
* I think your commit might solve the two issues, but could you provide a proof of your work? a GIF or an image will do.
* is it too much asking you having two different PRs for the two tickets? so we can track them easily.
* one of your commit failed the travis CI due to the mere numbers of text in a line. could you split the line?

**Comment by lucernae** [comment]
LGTM for my side.
Sorry travis only checks flake8 for now. Haven't got time to figure out how to create unittest for this repo 😄 

A nice have for the future is to implement this legend as leaflet plugin if possible, so it can be easy to attach/detach, or popup/hide. This will help users for smaller screen or mobile page. 
I explained this more on issue #192

**Comment by akbargumbira** [comment]
@boney-bun I fixed the failed travis issue. For the 2 PRs, I know that this is bad, I forgot that I still worked on branch 2.6.x. But if I remove one commit and make another PR, it would probably be more messy since I already reference this PR in the 2 issues solved. For the GIF one, I tried but not sure why my computer is always crashing when rendering the GIF using peek. Will look another apps to try..

**Comment by lucernae** [comment]
Yes, it's difficult to find a nice GIF maker in ubuntu 👍 . Let me know it if you find a nice one. 
For the issue with one PR fixing 2 different issue. I think that is fine for this one, and keep that in mind for next PR 😉 . Also, can you do a squash merge when you merge it?

**Pull request merged**
