### PR TITLE
improve report download buttons

### LINKED ISSUE #224: Improve report download buttons layout and text
- [x] space missing between `keep` and the `Close` button
- [x] use `Save Report` or `Save Results` instead of `Keep`?
- [x] make it more clear that `Download Report` provides a bundle of the map + table
- [ ] add an option to allow downloading of impacted features (actual data)?

screen shot 2017-09-12 at 10 16 52

### PR DESCRIPTION
**Pull request by boney-bun**
fix #224 

Below is the proposed new layout:
screen shot 2017-09-24 at 2 12 19 am

### CODE REVIEW

**Comment by gubuntu** [comment]
LGTM

**Comment by boney-bun** [comment]
the GIF:
improvereport

*Note:* this commit depends on kartoza/geonode#347

**Comment by lucernae** [comment]
This is small change. I think you can merge it @boney-bun. Thanks!

**Review by lucernae — APPROVED** [review]
LGTM

**Comment by boney-bun** [comment]
thanks @lucernae 
i'll merge now

**Pull request merged**
