### PR TITLE
change Impact Layer into Result based on issue: https://github.com/ka…

### PR DESCRIPTION
**Pull request by boney-bun**
#77

### CODE REVIEW

**Comment by lucernae** [comment]
You can write like this to link it to issue: #77

**Comment by boney-bun** [comment]
thanks @lucernae as this is a duplicate of #77, can we just remove the ticket?

**Comment by lucernae** [comment]
> thanks @lucernae as this is a duplicate of #77, can we just remove the ticket?

No, this is a different branch, so it will show up here. Don't worry about this.

For that next commit, could you provide some context on what the PR is all about.
Or you can link the issue number in the commit message.
Additionally, if it is UI related, you can also take some snapshots or GIF record, to show other what has changed.

Take a look at this example:
https://github.com/kartoza/geosafe/pull/47

Notice that if Reviewer is giving LGTM (Looks Good to Me), that means you have his/her approval.

**Comment by lucernae** [comment]
LGTM, if that's all.
Use Rebase and merge.

**Pull request merged**
