### PR TITLE
add tagline

### PR DESCRIPTION
**Pull request by boney-bun**
fix #139

### CODE REVIEW

**Comment by boney-bun** [comment]
@carina1000 do the font and size should exactly the same as in the OP?

Here is how the tagline shows up:
screen shot 2018-09-20 at 11 49 40 am

**Comment by carina1000** [comment]
Hi @boney-bun - this is fine for now :)

**Comment by boney-bun** [comment]
i wonder would this PR still valid @carina1000 ?
we have another issue regarding the geonode skin kartoza/geonode#420.

**Comment by gubuntu** [comment]
@boney-bun @carina1000 please work the tagline into the INGC skin and implement as an enhancement and close this when done. The tegline should be in the standard GeoSAFE skin (on testing and staging) whereas the INGC skin should ONLY appear in the INGC instance (cc @lucernae) and not on testing or staging. On the INGC instance it needs to be in PT

__Análise realista de impacto de risco natural - InaSAFe facilitada__

@raisserafael speak up if that's not the right translation

**Comment by lucernae** [comment]
@gubuntu @boney-bun @carina1000 Can we close this one or keep the tagline for standard GeoSAFE?

**Comment by boney-bun** [comment]
@lucernae i think we should keep as vanilla geosafe.

**Comment by gubuntu** [comment]
@boney-bun pls go ahead and merge into the vanilla GeoSAFE theme.

It is aready in the INGC theme.

**Comment by boney-bun** [comment]
thanks @lucernae @gubuntu 
i'm going to merge this PR

**Pull request merged**
